//
// Created by lperalta on 1/9/2022.
//

#ifndef EJERCICIOS_CPLUSPLUS_ORDERS_H
#define EJERCICIOS_CPLUSPLUS_ORDERS_H

enum Orders {
    ASCENDING,
    DESCENDING,
    NONE
};

#endif //EJERCICIOS_CPLUSPLUS_ORDERS_H
